### ISSUE TITLE
Instance of analyzer cannot be created: cannot find Microsoft.CodeAnalysis

### ISSUE THREAD

**Issue by jgcodes2020** [X9VoiD/WaylandSharp#1] opened 2022-08-02 02:31 UTC
## Error message
This was copied from Rider.

>  An instance of analyzer WaylandSharpGen.WlBindingGenerator cannot be created from /home/jgcodes/.nuget/packages/waylandsharp/0.2.1/analyzers/dotnet/cs/WaylandSharpGen.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified..

## Build environment
OS: Linux (ArcoLinux KDE)
IDE: Rider 2022.1.2
`dotnet` version: 6.0.106

By the looks of things, it also results in the generator not correctly building the bindings.

**Comment by X9VoiD** [comment] 2022-08-03 06:20
May I see what your `.csproj` looks like? I can't reproduce your issue (I mainly only use vim and vscode so that might also be a factor). There exists a [unit test](https://github.com/X9VoiD/WaylandSharp/blob/7b212bc8a53e8e64fcd98094bfbbdbcaea2301b6/src/WaylandSharp.Tests/Client/WlClientBuilderTest.cs#L688) which guarantees that under "expected circumstances", the generator will always create valid code, so it's likely an external problem.

**Comment by jgcodes2020** [comment] 2022-08-03 20:32
This is my `.csproj` file (GTK assembly for an Eto.Forms project):
```csproj
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <RootNamespace>M64RPFW.Gtk</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\M64RPFW\M64RPFW.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Eto.Platform.Gtk" Version="2.7.0" />
        <PackageReference Include="GdkSharp" Version="3.24.24.38" />
        <PackageReference Include="GtkSharp" Version="3.24.24.38" />
        <PackageReference Include="OpenTK" Version="4.7.4" />
        <PackageReference Include="WaylandSharp" Version="0.2.1" />
        <PackageReference Include="X11" Version="1.0.6" />
    </ItemGroup>


    <ItemGroup>
        <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="WaylandProtocol" />
        <AdditionalFiles Include="Interfaces\Wayland\wayland.xml" WaylandProtocol="client" />
    </ItemGroup>
</Project>
```
This is the structure of that project. I use Rider (ignore the dependencies section, it's not a real file).
![image](https://user-images.githubusercontent.com/35639051/182706096-2878f5a5-278b-4945-a79f-1c2078081582.png)

I also know that the generator will work properly again (but only once) if I delete the installed NuGet package and restore the project.

**Comment by jgcodes2020** [comment] 2022-08-03 21:12
The error also only seems to happen when I rename the project or any file paths relating to it.

**Comment by X9VoiD** [comment] 2022-08-04 05:59
There's nothing in the structure or project file that strikes me as "unexpected". When the error happens, does it at least build with `dotnet build` or `dotnet publish`?

**Comment by jgcodes2020** [comment] 2022-08-04 15:40
nope, not at all. I'm currently working around it by copying a previously generated file into my source code and using that

**Comment by X9VoiD** [comment] 2022-08-05 06:35
Would you be able to make a minimal reproduction of the issue? Just zipping a small project is fine, and the steps required to repro the issue.

**Comment by jgcodes2020** [comment] 2022-08-05 19:28
Here's a very minimal demonstration using the console template:  
[WlSharpTest1.tar.gz](https://github.com/X9VoiD/WaylandSharp/files/9271154/WlSharpTest1.tar.gz)

This is the output of `dotnet build` from that project.
![image](https://user-images.githubusercontent.com/35639051/183147482-f384b9ca-a726-445b-a911-2cadabefa78e.png)

**Comment by X9VoiD** [comment] 2022-08-05 20:35
Weird, it builds just fine on my side.
![image](https://user-images.githubusercontent.com/10338031/183158509-0114f9ab-3615-4d96-9579-3a3595308f90.png)
I'm still not sure what could possibly cause an issue on your end. Probably try deleting your whole `.nuget` folder and then run `dotnet build` after?

**Comment by jgcodes2020** [comment] 2022-08-06 01:42
`rm -rf`ing the `.nuget` folder does not help:
![image](https://user-images.githubusercontent.com/35639051/183228692-c15aa865-ed12-4475-a9d3-a77ecebcb705.png)
I'll try reinstalling .NET and seeing if that helps.

**EDIT:** that doesn't help either.

**Comment by X9VoiD** [comment] 2022-08-06 05:19
Maybe try spinning up a clean new container with podman or something just for the sake of testing.

```
cd dir/to/WlSharpTest1
podman run --rm -v $(pwd):/wl -w /wl mcr.microsoft.com/dotnet/sdk:6.0 dotnet build -c release -o out
```
> replace podman with docker if you don't have podman and prefer docker

This ensures that the build is not affected by the host environment, and that most of the stuff is "reproducible" (not completely but it's near). However, if this works then it just proves that there is indeed something wrong with the host environment. At that point you may close this issue but I will still try to help to the best of my abilities.

**Comment by X9VoiD** [comment] 2022-10-11 10:40
Closing stale issue, but feel free to reopen.

**Closed as not planned by X9VoiD** 2022-10-11 10:40 UTC

**Comment by jgcodes2020** [comment] 2023-03-13 02:35
This issue seems to be gone, I'll make a PR to document the correct .csproj options. It was probably an issue with setting up the .csproj file, and the default `wayland.xml` thing doesn't work.
